-- Create Database
CREATE DATABASE Cafe_Mood_Tracker 



-- Create Table 
CREATE TABLE cafe_orders
(order_id INT PRIMARY KEY,	
order_date DATE,
order_time TIME,
customer_id VARCHAR(10),	
item_name VARCHAR(50),
category VARCHAR(30),
price DECIMAL(8,2),
quantity INT,
weather	VARCHAR(20),
temperature	DECIMAL(4,1),
humidity INT,
customer_mood VARCHAR(20),	
payment_method VARCHAR(20),
dine_type VARCHAR(20),
total_amount DECIMAL(10,2)
);



-- See The Data
SELECT * FROM cafe_orders
LIMIT 10;

SELECT COUNT(*) FROM cafe_orders;



-- Data Cleaning
SELECT * FROM cafe_orders
WHERE order_id	IS NULL 
OR
order_date IS NULL 
OR
order_time IS NULL 
OR
customer_id	IS NULL 
OR
item_name IS NULL 
OR
category IS NULL 
OR
price IS NULL 
OR
quantity IS NULL 
OR
weather	IS NULL 
OR
temperature	IS NULL 
OR
humidity IS NULL 
OR
customer_mood IS NULL 
OR
payment_method IS NULL 
OR
dine_type IS NULL 
OR
total_amount IS NULL ;



-- Delete Null Data
DELETE FROM cafe_orders
WHERE order_id	IS NULL 
OR
order_date IS NULL 
OR
order_time IS NULL 
OR
customer_id	IS NULL 
OR
item_name IS NULL 
OR
category IS NULL 
OR
price IS NULL 
OR
quantity IS NULL 
OR
weather	IS NULL 
OR
temperature	IS NULL 
OR
humidity IS NULL 
OR
customer_mood IS NULL 
OR
payment_method IS NULL 
OR
dine_type IS NULL 
OR
total_amount IS NULL ;



-- Problems & Solutions

------------------------------------------Basic Business Analysis-------------------------------------------
--1. How many orders were placed in total?
SELECT COUNT(*) AS total_order
FROM cafe_orders;

--2. What is the total revenue generated by the café?
SELECT SUM(total_amount) AS total_revenue
FROM cafe_orders;

--3. What is the average order value?
SELECT ROUND(AVG(total_amount),2) AS avg_order_value
FROM cafe_orders;

--4. Which menu item was ordered the most?
SELECT item_name, COUNT(*) AS order_times
FROM cafe_orders
GROUP BY item_name
ORDER BY order_times DESC
LIMIT 1;

--5. Which menu category generated the highest revenue?
SELECT category, SUM(total_amount) AS total_revenue
FROM cafe_orders
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;

--6. Which payment method is used most frequently?
SELECT payment_method, COUNT(payment_method) AS times_used
FROM cafe_orders
GROUP BY payment_method
ORDER BY times_used DESC
LIMIT 1;

--7. How many orders were Dine-In versus Takeaway?
SELECT dine_type, COUNT(*) AS no_of_orders
FROM cafe_orders
GROUP BY dine_type
ORDER BY no_of_orders DESC;

--8. Which weather condition occurred most frequently?
SELECT weather, COUNT(*) AS occured_times
FROM cafe_orders
GROUP BY weather
ORDER BY occured_times DESC
LIMIT 1;



----------------------------------------Sales & Customer Behaviour Analysis----------------------------------------
--9. Which are the top 5 menu items based on total revenue?
SELECT item_name, SUM(total_amount) AS total_revenue
FROM cafe_orders
GROUP BY item_name
ORDER BY total_revenue DESC
LIMIT 5;

--10. Which weather condition generated the highest revenue?
SELECT weather, SUM(total_amount) AS total_revenue
FROM cafe_orders
GROUP BY weather
ORDER BY total_revenue
LIMIT 1;

--11. Which customer mood resulted in the highest average spending?
SELECT customer_mood, ROUND(AVG(total_amount), 2) AS average_spending
FROM cafe_orders
GROUP BY customer_mood
ORDER BY average_spending DESC
LIMIT 1;

--12. During which hour of the day does the café receive the most orders?
SELECT EXTRACT(HOUR FROM order_time) AS order_hour, COUNT(*) AS total_orders
FROM cafe_orders
GROUP BY order_hour
ORDER BY total_orders DESC
LIMIT 1;

--13. Which day of the week generates the highest revenue?
SELECT TO_CHAR(order_date, 'Day') AS week_Day, SUM(total_amount) AS total_revenue
FROM cafe_orders
GROUP BY week_day
ORDER BY total_revenue DESC
LIMIT 1;

--14. Which month records the highest total sales?
SELECT TO_CHAR(order_date, 'Month') AS month_name, SUM(total_amount) AS total_sales
FROM cafe_orders
GROUP BY month_name
ORDER BY total_sales DESC
LIMIT 1;

--15. Which menu category sells the most items?
SELECT category, SUM(quantity) AS total_items
FROM cafe_orders
GROUP BY category
ORDER BY total_items DESC
LIMIT 1;

--16. Which payment method contributes the highest revenue?
SELECT payment_method, SUM(total_amount) AS total_amount
FROM cafe_orders
GROUP BY payment_method
ORDER BY total_amount DESC
LIMIT 1;



---------------------------------------Weather & Mood Analysis-------------------------------------
--17. Which menu item is the most popular during rainy weather?
SELECT item_name, SUM(quantity) AS quantity_sold
FROM cafe_orders
WHERE weather = 'Rainy'
GROUP BY item_name
ORDER BY quantity_sold DESC
LIMIT 1;

--18. Which menu item is the most popular during sunny weather?
SELECT item_name, SUM(quantity) AS quantity_sold
FROM cafe_orders
WHERE weather = 'Sunny'
GROUP BY item_name
ORDER BY quantity_sold DESC
LIMIT 1;

--19. Which customer mood is most common during rainy weather?
SELECT customer_mood, COUNT(*) AS total
FROM cafe_orders
WHERE weather = 'Rainy'
GROUP BY customer_mood
ORDER BY total DESC
LIMIT 1;

--20. Which weather condition has the highest average order value?
SELECT weather, ROUND(AVG(total_amount),2) AS avg_order_value
FROM cafe_orders
GROUP BY weather
ORDER BY avg_order_value DESC
LIMIT 1;

--21. Which menu categories perform best under each weather condition?
WITH category_revenue AS
(SELECT weather, category, SUM(total_amount) AS total_revenue
FROM cafe_orders
GROUP BY weather, category),

ranked_categories AS
(SELECT weather, category, total_revenue,
RANK() OVER(PARTITION BY weather ORDER BY total_revenue DESC) AS revenue_rank 
FROM category_revenue)

SELECT weather, category, total_revenue
FROM ranked_categories
WHERE revenue_rank = 1 
ORDER BY weather;

--22. Which menu items are most preferred by Happy customers?
SELECT item_name, SUM(quantity) AS preferred_items
FROM cafe_orders
WHERE customer_mood = 'Happy'
GROUP BY item_name
ORDER BY preferred_items DESC
LIMIT 1;

--23. Which menu items are most preferred by Stressed customers?
SELECT item_name, SUM(quantity) AS preferred_items
FROM cafe_orders
WHERE customer_mood = 'Stressed'
GROUP BY item_name
ORDER BY preferred_items DESC
LIMIT 1;



-----------------------------------Time-Based Analysis----------------------------------------
--24. What are the most popular menu categories during the morning (6 AM–11 AM)?
SELECT category, SUM(quantity) AS total_item 
FROM cafe_orders
WHERE order_time >= '06:00:00' 
AND order_time <= '11:00:00'
GROUP BY category
ORDER BY total_item DESC;

--25. What are the most popular menu categories during the evening (5 PM–10 PM)?
SELECT category, SUM(quantity) AS total_item
FROM cafe_orders
WHERE order_time >= '17:00:00' 
AND order_time <= '22:00:00'
GROUP BY category
ORDER BY total_item DESC;

--26. Compare the average spending of Morning, Afternoon, and Evening customers.
SELECT 
	CASE 
		WHEN order_time >= '06:00:00' 
		AND order_time < '12:00:00' THEN 'Morning'
		
		WHEN order_time >= '12:00:00' 
		AND order_time < '17:00:00' THEN 'Afternoon'
		
		WHEN order_time >= '17:00:00' 
		AND order_time < '22:00:00' THEN 'Evening'
	END AS time_period,
	
ROUND(AVG(total_amount),2) AS average_spending
FROM cafe_orders
GROUP BY time_period
ORDER BY average_spending DESC;



----------------------------------Advanced Business Insights--------------------------------------
--27. Rank all menu items by total revenue within each category. (Window Functions)
WITH all_menu AS
(SELECT item_name, category, SUM(total_amount) AS total_revenue
FROM cafe_orders
GROUP BY item_name, category),

ranked_items AS 
(SELECT item_name, category, total_revenue,
RANK() OVER(PARTITION BY category ORDER BY total_revenue DESC)AS item_rank
FROM all_menu)

SELECT item_name, category, total_revenue, item_rank
FROM ranked_items
ORDER BY category, item_rank;

--28. Find the top-selling menu item for each weather condition. 
WITH item_sales AS
(SELECT item_name, weather, SUM(quantity) AS total_quantity
FROM cafe_orders
GROUP BY item_name, weather),

ranked_items AS
(SELECT item_name, weather, total_quantity,
RANK() OVER(PARTITION BY weather ORDER BY total_quantity DESC)AS item_rank
FROM item_sales)

SELECT item_name, weather, total_quantity
FROM ranked_items
WHERE item_rank = 1
ORDER BY weather;

--29. Which top 10 customers spent the most in the café?
SELECT customer_id, SUM(total_amount) AS total_spent
FROM cafe_orders
GROUP BY customer_id
ORDER BY total_spent DESC
LIMIT 10;

--30. What percentage of the café's total revenue comes from each menu category?(Aggregate Functions + Percentage Calculation)
SELECT category, SUM(total_amount) AS category_revenue,
ROUND(SUM(total_amount) * 100.0 /
(SELECT SUM(total_amount)FROM cafe_orders),2) AS revenue_percentage
FROM cafe_orders
GROUP BY category
ORDER BY revenue_percentage DESC;



-------------------------------------------End Of Project-------------------------------------------
